name: Portfolio-Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu
    steps:
    - name: checkout 
      uses: actions/checkout@v4

    - name: configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
       aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1

    - name: Deploy the static site to s3 bucket
      run: aws s3 sync . s3://portfolio-app-development --delete
